services:

  mediawiki:
    environment:
      - HOST_IP=${HOST_IP}
      - TEST_USER_UUID=${TEST_USER_UUID}
      - CLIENT_UUID=${CLIENT_UUID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    volumes:
      - ../../.env:/root/.env
    ports:
      - 8888:8080
    environment:
      - HOST_IP=${HOST_IP}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
