name: EventBus
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/EventBus
dependencies:
  - EventStreamConfig
configuration: |
  wfLoadExtension( 'EventBus' );
bash: |
  cd /var/www/html/w/extensions/EventBus
  composer install --no-dev