name: GlobalWatchlist
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/GlobalWatchlist
configuration: |
  wfLoadExtension( 'GlobalWatchlist' );
bash: |
  cd /var/www/html/w/extensions/GlobalWatchlist
  composer install --no-dev
  npm install
  cd /var/www/html/w
  composer update
  php maintenance/update.php
