name: RelatedArticles
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/RelatedArticles
configuration: |
  wfLoadExtension( 'RelatedArticles' );
bash: |
  cd /var/www/html/w/extensions/RelatedArticles
  composer install --no-dev
  cd /var/www/html/w
  composer update
  php maintenance/update.php