name: WikimediaMessages
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/WikimediaMessages
configuration: |
  wfLoadExtension( 'WikimediaMessages' );
bash: |
  cd /var/www/html/w/extensions/WikimediaMessages
  composer install --no-dev