name: WikimediaEvents
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/WikimediaEvents
configuration: |
  wfLoadExtension( 'WikimediaEvents' );
  $wgWMEStatsdBaseUri = '/beacon/statsv';
bash: |
  cd /var/www/html/w/extensions/WikimediaEvents
  composer install --no-dev