name: IPInfo
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/IPInfo
configuration: |
  wfLoadExtension( 'IPInfo' );
  $wgGroupPermissions['*']['ipinfo'] = true;
  $wgGroupPermissions['*']['ipinfo-view-basic'] = true;
  $wgGroupPermissions['*']['ipinfo-view-full'] = true;
  $wgGroupPermissions['*']['ipinfo-view-log'] = true;
bashScripts: |
  cd /var/www/html/w/extensions/IPInfo
  composer install --no-dev