name: UrlShortener
repository: https://gerrit.wikimedia.org/r/mediawiki/extensions/UrlShortener
configuration: |
  wfLoadExtension( 'UrlShortener' );
bashScripts: |
  cd /var/www/html/w/extensions/UrlShortener
  composer install --no-dev