version: '3.7'
services:
  mediawiki:
    volumes:
      - ../selenium/wdio.conf.override.js:/var/www/html/w/tests/selenium/wdio.conf.override.js
      - ../selenium/selenium-preparation.sh:/var/www/html/w/selenium-preparation.sh
      - ../selenium/puppeteer-chromium-version-finder.js:/var/www/html/w/puppeteer-chromium-version-finder.js
    environment:
      - MW_SERVER=http://mediawiki-mediawiki-web-1:8080